TEXT_EMBEDDINGS_DIMENSIONS = 1024
TEXT_CHUNK_SIZE = 425
TEXT_OVERLAP = 0.25

ANNOTATION_EMBEDDINGS_DIMENSIONS = 512
TAGS_ANNOTATIONS_CHUNK_SIZE = 256
TAGS_ANNOTATIONS_OVERLAP = 0.05

BM25_KOEF = 0.15
EMBED_KA_KOEF = 0.15
EMBED_T_KOEF = 0.7

FAISS_ANNOTATION_K = 5 # Топ K при поиске в faiss
FAISS_TEXT_K = 12 # Топ K при поиске в faiss
BM25_TOPK = 8 # Top k для BM25
TOP_K = 12 # Топ K документов для RAG
KLLM = 6